In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3]) #declaration

In [6]:
print(a) 

[1 2 3]


In [8]:
print(a.shape)#analysis says 1d 2d or 3d the shape of array

(3,)


In [10]:
print(a.dtype)#data type of the array 

int64


In [12]:
print(a.ndim)#dimension of the array

1


In [14]:
print(a.size)#no. of elements in the array

3


In [16]:
print(a.itemsize)#bite size of each element

8


In [18]:
print(a[0])#access of each element

1


In [22]:
b=np.array([2,0,2])*a #array multiplications with same size 
print(b)

[2 0 6]


In [30]:
#list vs arrays
l=[1,2,3]
a=np.array([1,2,3])
print(l)
print(a)
#different type of representation 

[1, 2, 3]
[1 2 3]


In [32]:
l.append(4)
print(l)
a.append(4)#not possible in numpy
print(a)

[1, 2, 3, 4]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [34]:
l=l+[4]
print(l)
a=a+np.array([4])#still does not append 
print(a)#instead adds 4 to each element 

[1, 2, 3, 4, 4]
[5 6 7]


In [44]:
l=l*2
print(l)#appends twice the same array to itself bellow its appended to many times due to reruns
a=a*2
print(a)#mulitplies 2 to each element 

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 4, 4]
[ 80  96 112]


In [48]:
a=np.sqrt(a)
print(a)


[ 8.94427191  9.79795897 10.58300524]


In [52]:
#dot product of vectors
#in lists
l1=[1,2,3]
l2=[4,5,6]
dot=0
for i in range(len(l1)):
    dot+=l1[i]*l2[i]
print(dot)

32


In [58]:
#in numpy
a1=np.array([1,2,3])
a2=np.array([4,5,6])
dot=np.dot(a1,a2)
print(dot)
dot=a1*a2#array mul
dot=np.sum(dot)#sum after mult 
#or dot=(a1*a2).sum()
#or dot=a1@a2
print(dot)

32
32


In [60]:
dot=a1@a2
print(dot)

32


In [66]:
#multi dimensional list
a=np.array([[1,2,3],[4,5,6]])
print(a.shape) #2x3 matrix

(2, 3)


In [68]:
print(a[0])#first row
print(a[0][0])#first row first col
print(a[0,0])

[1 2 3]
1
1


In [70]:
print(a[:,0])
#print column

[1 4]


In [74]:
#transpose
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [78]:
#inverse only square matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(a))
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [80]:
print(np.linalg.det(a))
#determinant

-2.0000000000000004


In [86]:
#diagonal matrix 
print(np.diag(a))#this is a diagonal vector
c=np.diag(a)
print(np.diag(c))#will give a daigonal matrix with elemnts fromt the vector 

[1 4]
[[1 0]
 [0 4]]


In [88]:
#slicing 
a=np.array([[1,2],[3,4]])
b=a[0,1]#first row sec col
print(b)

2


In [90]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a[0,:]
print(b)#only first row

[1 2 3 4]


In [92]:
b=a[:,1]
print(b)#only second column

[2 6]


In [94]:
b=a[-1,-1]
print(b)#last row last column

8


In [100]:
a=np.array([10,19,30,41,5,6])
print(a)
even=np.argwhere(a%2==0).flatten()#finds indices of even elements 
print(a[even])#print even elements

[10 19 30 41  5  6]
[10 30  6]


In [7]:
#reshaping
a=np.arange(1,7)
print(a)
print(a.shape)
b=a.reshape((2,3))
print(b)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]


In [11]:
a=np.arange(1,7)
print(a)
print(a.shape)
b=a[np.newaxis,:]
print(b)
print(b.shape)
c=a[:,np.newaxis]
print(c)
print(c.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [17]:
#concatenation
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[5,6]])
c=np.concatenate((a,b),axis=0)#or axis=None
print(c)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [19]:
c=np.concatenate((a,b.T),axis=1)
print(c)

[[1 2 5]
 [3 4 6]]


In [21]:
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
c=np.hstack((a,b))#horizontal stack
print(c)
d=np.vstack((a,b))#vertical stack
print(d)

[1 2 3 4 6 7 8 9]
[[1 2 3 4]
 [6 7 8 9]]


In [23]:
#broadcasting
x=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
a=np.array([1,0,1])
y=x+a#adding this to all the rows to each corresponding element
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


In [33]:
#functions and axis
a=np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)
print(a.sum(axis=1))
print(a.mean(axis=0))
print(a.std(axis=None))
print(a.min(axis=1))

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
[ 70 140]
[12. 13. 14. 15. 16. 17. 18.]
5.385164807134504
[ 7 17]


In [5]:
#generating arrays
a=np.zeros((2,3))
print(a)
a=np.ones((2,3))
print(a)
a=np.full((2,3),5.0)
print(a)
a=np.eye(3)
print(a)
a=np.arange(20)
print(a)
a=np.linspace(0,10,5)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.   2.5  5.   7.5 10. ]


In [55]:
#generating random arrays
a= np.random.random((3,2))#0-1
print(a)
a=np.random.randn(3,2)#normal/gaussian
print(a)
print(a.mean())
print(a.var())
a=np.random.randint(3,10,size=(3,3))
print(a)
a=np.random.choice((-8,-7,-6),size=10)
print(a)

[[0.94561888 0.47561663]
 [0.03357327 0.7941715 ]
 [0.58338709 0.10492589]]
[[-0.77784448  1.71731917]
 [ 0.19014704  1.00895613]
 [ 1.59900199 -2.53888681]]
0.19978217132817586
2.2286086027121192
[[3 8 9]
 [8 5 3]
 [6 5 3]]
[-8 -8 -7 -7 -8 -6 -8 -6 -6 -6]


In [59]:
#linear algebra
a=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors= np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)#column vector
#e_vec * e_val =A*e_vec
b=eigenvectors[:,0]*eigenvalues[0]
print(b)
b=a@eigenvectors[:,0]
print(b)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


In [63]:
#solving linear systems 
#x1+x2=2200
#1.5x1 +4x2=5050
#x=[x1 x2] A=([1 1],[1.5 4]) b=[2200 5050] x= A^-1 B
A=np.array([[1,1],[1.5,4.0]])
b=np.array([2200,5050])
x=np.linalg.inv(A).dot(b)
print(x)

[1500.  700.]


In [ ]:
#import csv files
#np.loadtxt
#np.genfromtxt
data=np.loadtxt('file.csv', delimeter=",",dtype=np.float32)